My very first attempt to refactor a code (don't judge too strict):)
Nikitos-U/smart-home-2019 pull request #1
Opened 2019-10-10 19:40 UTC by Nikitos-U

2019-10-15 21:59 UTC, a-ivanov requested changes

2019-10-15 21:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HomeCondition.java
> +    static SmartHome readHomeCondition() throws IOException {
А если мы захотим читать состояние дома по сети, а не из файла? Добавьте абстракцию.

2019-10-15 21:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HomeCondition.java
> +class HomeCondition {
Condition - это условие, наверное, вы имели в виду состояние?

2019-10-15 21:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SensorEvent.java
> +    static SensorEvent getNextSensorEvent() {
Нарушен SRP - класс хранит состояние события и читает следующее событие. Исправьте.

2019-10-15 21:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SensorEventType.java
> +            return new LightEventHandler(type, objectId, smartHome);
Тип события - не лучшее место для разменщения конфигурационного кода. Подумайте, куда его можно переместить и исправьте.

2019-10-15 21:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +    static void sendCommand(SensorCommand command) {
Нарушен SRP - отправка команды и обработка событий. Исправьте.

2019-10-15 21:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/LightEventHandler.java
> +        super(type,objectId,smartHome);
Конструктор используется для инициализации полей класса, а не для размещения бизнес логики. Исправьте.

2019-10-15 21:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +    public DoorEventHandler(SensorEventType type, String objectId,SmartHome smartHome) {
См. замечание для LightEventHandler.

2019-10-15 21:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +                        if (room.getName().equals("hall")) {
Нарушен SRP - обработка события двери и сценария "умнго дома". Исправьте.

2019-10-17 13:09 UTC, Nikitos-U commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +                        if (room.getName().equals("hall")) {
Исправил указанные ошибки:
https://github.com/Nikitos-U/smart-home-2019/pull/1/commits/7b691d1ab5573c8b4a497e9bf0882449b3b2ba43

2019-10-17 13:10 UTC, Nikitos-U commented
Исправил указанные ошибки:
https://github.com/Nikitos-U/smart-home-2019/pull/1/commits/7b691d1ab5573c8b4a497e9bf0882449b3b2ba43

2019-10-22 22:33 UTC, a-ivanov requested changes
Уже хорошо - надо немного доделать.

2019-10-22 22:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HomeCondition.java
> +     SmartHome readCondition() throws IOException;
Leaky abstraction: детали имплементации (читаем из файла) видны в интерфейсе (абстракции). Исправьте.

2019-10-22 22:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HandlerType.java
> +    LightEvent(new LightEventHandler()), DoorEvent(new DoorEventHandler());
Раз уж на то пошло, в Java enum инстансы принято называть всеми заглавными с "_" на месте пробелов.

2019-10-22 22:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +    static void sendCommand(SensorCommand command) {
Не исправлено.

2019-10-22 22:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +                        for (ScenarioTypes value : ScenarioTypes.values()) {
Нарушение SRP - обработчик работает над событиями дверей и "умного дома". Исправьте.

2019-10-22 22:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ScenarioTypes.java
> +    CloseAllDoors(new AllDoorsCloseScenario());
Инстансы enum - заглавными.

2019-11-06 21:31 UTC, Nikitos-U commented on src/main/java/ru/sbt/mipt/oop/HomeCondition.java
> +     SmartHome readCondition() throws IOException;
Может быть туплю, но не понимаю в чем это выражается. Есть отдельный интерфейс, с методом, который перегружается в наследующих классах, в зависимости от источника данных.

2019-11-07 04:37 UTC, sbt-agoshkov commented
Ну у вас в интерфейсе написано throws IOException.Что как бы намекает на чтение из файла.А если бы первой реализацией было чтение из базы данных,  вы бы добавили throws SQLException?Уберите throws просто.0:31, 7 ноября 2019 г., "Nikitos-U" <notifications@github.com>:@Nikitos-U commented on this pull request.



In src/main/java/ru/sbt/mipt/oop/HomeCondition.java:
> @@ -0,0 +1,7 @@
+package ru.sbt.mipt.oop;
+
+import java.io.IOException;
+
+public interface HomeCondition {
+     SmartHome readCondition() throws IOException;

Может быть туплю, но не понимаю в чем это выражается. Есть отдельный интерфейс, с методом, который перегружается в наследующих классах, в зависимости от источника данных.

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.
Илья

2019-11-07 10:04 UTC, Nikitos-U commented
Исправил указанные ошибки   @a-ivanov, @sbt-agoshkov

2019-11-12 22:45 UTC, a-ivanov requested changes
По 1му ок, но не могу поставить зачет, пока не будет исправлен DoorEventHandler - он вызывает AllDoorsCloseScenario, а AllDoorsCloseScenario должен быть отдельным обработчиком (это SRP, например, мы захотим легко отключить обработку сценариев умного дома).

2019-11-13 08:58 UTC, Nikitos-U commented
@a-ivanov Исправил DoorEventHandler

2019-11-25 12:07 UTC, a-ivanov approved these changes

2019-11-26 20:18 UTC, merged